insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (1, 'loja', '10397 Scoville Trail', 22, 63);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (2, 'casa', '66339 Swallow Center', 89, 6);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (3, 'apartamento', '4820 Drewry Street', 86, 38);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (4, 'casa', '300 Boyd Parkway', 55, 54);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (5, 'loja', '18422 Lerdahl Avenue', 45, 41);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (6, 'casa', '38 Trailsway Point', 33, 14);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (7, 'casa', '65385 Butternut Center', 45, 35);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (8, 'apartamento', '65751 Coolidge Crossing', 26, 3);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (9, 'apartamento', '5 Fisk Alley', 96, 15);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (10, 'apartamento', '2275 Barby Circle', 28, 32);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (11, 'apartamento', '2392 Ronald Regan Place', 68, 46);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (12, 'apartamento', '5 Manufacturers Terrace', 66, 23);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (13, 'escritório', '73326 Ronald Regan Lane', 83, 54);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (14, 'loja', '1 Blackbird Center', 33, 100);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (15, 'loja', '0919 Randy Center', 29, 45);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (16, 'casa', '5 Schlimgen Drive', 37, 32);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (17, 'loja', '62031 Fisk Avenue', 86, 29);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (18, 'casa', '7726 Rusk Lane', 15, 30);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (19, 'loja', '3 South Park', 77, 62);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (20, 'escritório', '21371 Waxwing Pass', 73, 66);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (21, 'escritório', '559 Old Shore Plaza', 87, 100);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (22, 'escritório', '89 Johnson Crossing', 2, 8);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (23, 'escritório', '45883 Hovde Park', 18, 84);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (24, 'escritório', '1 Grasskamp Crossing', 73, 25);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (25, 'apartamento', '462 Bay Hill', 15, 12);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (26, 'apartamento', '1 Old Shore Parkway', 68, 70);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (27, 'escritório', '750 Daystar Point', 71, 6);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (28, 'apartamento', '816 Annamark Court', 77, 33);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (29, 'loja', '41752 Swallow Place', 67, 13);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (30, 'escritório', '62 Kingsford Hill', 5, 40);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (31, 'loja', '821 Rutledge Circle', 100, 23);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (32, 'casa', '24958 Summer Ridge Terrace', 61, 63);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (33, 'escritório', '07 Esker Crossing', 41, 83);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (34, 'apartamento', '4 Duke Drive', 25, 27);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (35, 'loja', '56071 East Lane', 92, 37);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (36, 'loja', '86595 Miller Terrace', 35, 75);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (37, 'casa', '40598 Park Meadow Alley', 77, 54);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (38, 'escritório', '56407 Birchwood Circle', 37, 68);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (39, 'escritório', '045 Schlimgen Hill', 13, 37);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (40, 'apartamento', '5 Manley Plaza', 88, 1);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (41, 'loja', '01296 Corry Point', 85, 19);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (42, 'casa', '36 Canary Junction', 39, 31);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (43, 'apartamento', '4152 Raven Court', 54, 17);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (44, 'apartamento', '076 Iowa Lane', 4, 3);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (45, 'apartamento', '285 Maple Wood Lane', 1, 55);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (46, 'apartamento', '08 Farmco Trail', 84, 88);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (47, 'escritório', '87 Shelley Center', 67, 30);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (48, 'escritório', '4 Village Plaza', 80, 39);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (49, 'casa', '63695 Bluejay Lane', 95, 92);
insert into instalacao (id, tipo, endereco, cliente_id, contrato_id) values (50, 'escritório', '60 Dryden Crossing', 76, 39);
